<a href="https://colab.research.google.com/github/wannaphongcom/Machine_Learning_Code/blob/master/and.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install skorch

     |████████████████████████████████| 102kB 2.7MB/s 


In [0]:
import torch
import numpy as np

In [0]:
x_train=[[0,0],[0,1],[1,0],[1,1]]
y_train=[[0],[0],[0],[1]]

In [0]:
tensor_X = torch.stack([torch.Tensor(i) for  i in x_train])

In [0]:
tensor_y = torch.stack([torch.Tensor(i) for  i in y_train])

In [383]:
tensor_X

tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])

In [384]:
tensor_y

tensor([[0.],
        [0.],
        [0.],
        [1.]])

In [0]:
model = torch.nn.Sequential(
    torch.nn.Linear(2, 2,True),
    torch.nn.Sigmoid(),
    torch.nn.Linear(2, 1,True),
)

In [404]:
print(model)

Sequential(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): Sigmoid()
  (2): Linear(in_features=2, out_features=1, bias=True)
)


In [0]:
loss_fn = torch.nn.MSELoss()
learning_rate = 1e-4

In [0]:
import torch.utils.data as utils

In [0]:
my_dataset = utils.TensorDataset(tensor_X,tensor_y)

In [0]:
my_dataloader = utils.DataLoader(my_dataset)

In [409]:
print(my_dataloader)

In [410]:
for batch_idx, (data, target) in enumerate(my_dataloader):
  print((data, target))

(tensor([[0., 0.]]), tensor([[0.]]))
(tensor([[0., 1.]]), tensor([[0.]]))
(tensor([[1., 0.]]), tensor([[0.]]))
(tensor([[1., 1.]]), tensor([[1.]]))


In [0]:
criterion = torch.nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [412]:
'''for i in range(10):
  for batch_idx, (data, target) in enumerate(my_dataloader):
    y_pred = model(data)
    loss = criterion(y_pred, tensor_y)
    print(t, loss.item())
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()'''

'for i in range(10):\n  for batch_idx, (data, target) in enumerate(my_dataloader):\n    y_pred = model(data)\n    loss = criterion(y_pred, tensor_y)\n    print(t, loss.item())\n    optimizer.zero_grad()\n    loss.backward()\n    optimizer.step()'

In [413]:
for i in range(5000):
  for x1,y1 in zip(tensor_X,tensor_y):
    optimizer.zero_grad()
    y_pred = model(x1)
    loss = criterion(y_pred, y1)
    print(t, loss.item())
    
    loss.backward()
    optimizer.step()

0 0.3080485761165619
0 0.24891233444213867
0 0.3007518947124481
0 0.2556101083755493
0 0.27521562576293945
0 0.22179773449897766
0 0.2693757116794586
0 0.2837170958518982
0 0.2473582774400711
0 0.19882898032665253
0 0.24273796379566193
0 0.31012994050979614
0 0.2236463874578476
0 0.17930956184864044
0 0.22005128860473633
0 0.3347826302051544
0 0.20339934527873993
0 0.16266880929470062
0 0.2006695419549942
0 0.3576640784740448
0 0.18605703115463257
0 0.1484379768371582
0 0.1840611696243286
0 0.3788020610809326
0 0.17115768790245056
0 0.13623099029064178
0 0.16978737711906433
0 0.3982521593570709
0 0.158319354057312
0 0.12572894990444183
0 0.15748518705368042
0 0.4160885512828827
0 0.14722520112991333
0 0.116667740046978
0 0.1468532830476761
0 0.4323976933956146
0 0.1376117616891861
0 0.10882793366909027
0 0.13764086365699768
0 0.44727224111557007
0 0.12925918400287628
0 0.10202676057815552
0 0.12963850796222687
0 0.46080827713012695
0 0.12198350578546524
0 0.0961114913225174
0 0.1226708

In [414]:
dir(model)

['__call__',
 '__class__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_apply',
 '_backend',
 '_backward_hooks',
 '_buffers',
 '_forward_hooks',
 '_forward_pre_hooks',
 '_get_item_by_idx',
 '_get_name',
 '_load_from_state_dict',
 '_load_state_dict_pre_hooks',
 '_modules',
 '_named_members',
 '_parameters',
 '_register_load_state_dict_pre_hook',
 '_register_state_dict_hook',
 '_slow_forward',
 '_state_dict_hooks',
 '_tracing_name',
 '_version',
 'add_module',
 'apply',
 'buffers',
 'children',
 'cpu',
 'cuda',
 'double',
 'dump_patches',
 'eval',
 'extra_repr',
 'float',
 'forward',
 'ha

In [415]:
model(data)

tensor([[0.7861]], grad_fn=<AddmmBackward>)

In [418]:
x = torch.FloatTensor([1,1])
model(x)

tensor([0.7861], grad_fn=<AddBackward0>)

In [417]:
data.shape

torch.Size([1, 2])