<a href="https://colab.research.google.com/github/wannaphongcom/Machine_Learning_Code/blob/master/and.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
!pip install torch

In [0]:
import torch
import numpy as np

In [0]:
x_train=[[0,0],[0,1],[1,0],[1,1]]
y_train=[[0],[0],[0],[1]]

In [0]:
tensor_X = torch.stack([torch.Tensor(i) for  i in x_train])

In [0]:
tensor_y = torch.stack([torch.Tensor(i) for  i in y_train])

In [24]:
tensor_X

tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])

In [25]:
tensor_y

tensor([[0.],
        [0.],
        [0.],
        [1.]])

In [0]:
model = torch.nn.Sequential(
    torch.nn.Linear(2, 2,True),
    torch.nn.Sigmoid(),
    torch.nn.Linear(2, 1,True),
)

In [27]:
print(model)

Sequential(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): Sigmoid()
  (2): Linear(in_features=2, out_features=1, bias=True)
)


In [0]:
loss_fn = torch.nn.MSELoss()
learning_rate = 1e-4

In [0]:
import torch.utils.data as utils

In [0]:
my_dataset = utils.TensorDataset(tensor_X,tensor_y)

In [0]:
my_dataloader = utils.DataLoader(my_dataset)

In [32]:
print(my_dataloader)

In [33]:
for batch_idx, (data, target) in enumerate(my_dataloader):
  print((data, target))

(tensor([[0., 0.]]), tensor([[0.]]))
(tensor([[0., 1.]]), tensor([[0.]]))
(tensor([[1., 0.]]), tensor([[0.]]))
(tensor([[1., 1.]]), tensor([[1.]]))


In [0]:
criterion = torch.nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [35]:
'''for i in range(10):
  for batch_idx, (data, target) in enumerate(my_dataloader):
    y_pred = model(data)
    loss = criterion(y_pred, tensor_y)
    print(t, loss.item())
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()'''

'for i in range(10):\n  for batch_idx, (data, target) in enumerate(my_dataloader):\n    y_pred = model(data)\n    loss = criterion(y_pred, tensor_y)\n    print(t, loss.item())\n    optimizer.zero_grad()\n    loss.backward()\n    optimizer.step()'

In [37]:
for i in range(5000):
  for x1,y1 in zip(tensor_X,tensor_y):
    optimizer.zero_grad()
    y_pred = model(x1)
    loss = criterion(y_pred, y1)
    print(i, loss.item())
    
    loss.backward()
    optimizer.step()

0 1.0636651515960693
0 0.974033772945404
0 0.8534932136535645
0 3.553042411804199
1 0.7425501942634583
1 0.6759786605834961
1 0.5920420289039612
1 3.009591817855835
2 0.512211799621582
2 0.4631946086883545
2 0.40539559721946716
2 2.5789217948913574
3 0.34765222668647766
3 0.31191831827163696
3 0.2727319300174713
3 2.2345211505889893
4 0.2309134602546692
4 0.20517636835575104
4 0.17916429042816162
4 1.9568699598312378
5 0.14898070693016052
5 0.13072754442691803
5 0.11394904553890228
5 1.7313874959945679
6 0.09236180782318115
6 0.07968129217624664
6 0.06927948445081711
6 1.5470471382141113
7 0.054104216396808624
7 0.04554937034845352
7 0.03945634141564369
7 1.3954170942306519
8 0.029102686792612076
8 0.023582810536026955
8 0.020307468250393867
8 1.269989252090454
9 0.013604724779725075
9 0.010301289148628712
9 0.008775024674832821
9 1.1656954288482666
10 0.004853434395045042
10 0.0031548882834613323
10 0.002618796657770872
10 1.0785584449768066
11 0.000826977367978543
11 0.00027868000324

In [38]:
dir(model)

['__call__',
 '__class__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_apply',
 '_backend',
 '_backward_hooks',
 '_buffers',
 '_forward_hooks',
 '_forward_pre_hooks',
 '_get_item_by_idx',
 '_get_name',
 '_load_from_state_dict',
 '_load_state_dict_pre_hooks',
 '_modules',
 '_named_members',
 '_parameters',
 '_register_load_state_dict_pre_hook',
 '_register_state_dict_hook',
 '_slow_forward',
 '_state_dict_hooks',
 '_tracing_name',
 '_version',
 'add_module',
 'apply',
 'buffers',
 'children',
 'cpu',
 'cuda',
 'double',
 'dump_patches',
 'eval',
 'extra_repr',
 'float',
 'forward',
 'ha

In [39]:
model(data)

tensor([[0.9143]], grad_fn=<AddmmBackward>)

In [40]:
x = torch.FloatTensor([1,1])
model(x)

tensor([0.9143], grad_fn=<AddBackward0>)

In [41]:
data.shape

torch.Size([1, 2])