# XOR In PyTorch

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.autograd import Variable

## เตรียมข้อมูล

เตรียมข้อมูลสำหรับใช้ train XOR โดยเราจะต้องนำข้อมูลไปผ่านให้กลายเป็น Tensor แล้วใช้ Variable เพื่อให้สามารถนำค่าไปใช้งานได้แล้วเก็บรวมไว้ใน list

In [2]:
import numpy as np 
X = list(map(lambda s: Variable(torch.Tensor([s])).cpu(), [
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
]))
y = list(map(lambda s: Variable(torch.Tensor([s])).cpu(), [
    [0],
    [1],
    [1],
    [0]
]))
#X = torch.from_numpy(np.array([[0,0],[0,1],[1,0],[1,1]]))
#y = torch.from_numpy(np.array([[0],[1],[1],[0]]))

เติม .cuda() เพื่อใช้ GPU ถ้าเติม .cpu() จะใช้ CPU โดย model ต้องเลือกให้สัมพันธ์กับข้อมูลว่าเป็น GPU หรือ CPU

In [3]:
X

[tensor([[0., 0.]]),
 tensor([[0., 1.]]),
 tensor([[1., 0.]]),
 tensor([[1., 1.]])]

In [4]:
X[0]

tensor([[0., 0.]])

In [5]:
Variable(X[0])

tensor([[0., 0.]])

In [6]:
y

[tensor([[0.]]), tensor([[1.]]), tensor([[1.]]), tensor([[0.]])]

In [7]:
X[0].shape[1]

2

In [8]:
input_num_units=X[0].shape[1]

In [9]:
hidden_num_units=8

In [10]:
output_num_units=1

In [11]:
epoch=1000

In [12]:
w = torch.randn(input_num_units, output_num_units)
b = torch.randn(hidden_num_units)

In [13]:
net = torch.nn.Sequential(
 torch.nn.Linear(input_num_units, hidden_num_units),
 torch.nn.Sigmoid(),
 torch.nn.Linear(hidden_num_units, output_num_units),
).cpu()

In [14]:
'''
class model(nn.Module):
    def __init__(self):
        super().__init__()
        # Inputs to hidden layer linear transformation
        self.hidden = nn.Linear(input_num_units, hidden_num_units)
        # Output layer, 10 units - one for each digit
        self.output = nn.Linear(hidden_num_units, output_num_units)
        
    def forward(self, x):
        # Hidden layer with sigmoid activation
        x = F.sigmoid(self.hidden(x))
        # Output layer with softmax activation
        x = self.output(x)#F.softmax(self.output(x))
        
        return x'''
#net=model().cuda()
loss_fn = nn.MSELoss()
net

Sequential(
  (0): Linear(in_features=2, out_features=8, bias=True)
  (1): Sigmoid()
  (2): Linear(in_features=8, out_features=1, bias=True)
)

In [15]:
net.forward

<bound method Sequential.forward of Sequential(
  (0): Linear(in_features=2, out_features=8, bias=True)
  (1): Sigmoid()
  (2): Linear(in_features=8, out_features=1, bias=True)
)>

In [16]:
net

Sequential(
  (0): Linear(in_features=2, out_features=8, bias=True)
  (1): Sigmoid()
  (2): Linear(in_features=8, out_features=1, bias=True)
)

In [17]:
#dir(net)

In [18]:
#model.parameters()

In [19]:
learning_rate = 0.1

In [20]:
import torch.optim as optim

# create your optimizer
optimizer = optim.SGD(net.parameters(), lr=learning_rate)

In [21]:
criterion = nn.MSELoss()

In [22]:
for i in range(0,epoch):  # trains the NN 1,000 times
    for input, target in zip(X, y):
        optimizer.zero_grad() 
        output = net(input)
        loss = criterion(output, target)
        loss.backward()
        optimizer.step()
    print("Epoch {: >8} Loss: {}%".format(i+1, loss.cpu().data.numpy()*100))

Epoch        1 Loss: 70.6503689289093%
Epoch        2 Loss: 79.41150665283203%
Epoch        3 Loss: 78.05562019348145%
Epoch        4 Loss: 76.57843828201294%
Epoch        5 Loss: 75.15897750854492%
Epoch        6 Loss: 73.79730939865112%
Epoch        7 Loss: 72.49055504798889%
Epoch        8 Loss: 71.23610973358154%
Epoch        9 Loss: 70.03152370452881%
Epoch       10 Loss: 68.874591588974%
Epoch       11 Loss: 67.76334643363953%
Epoch       12 Loss: 66.69585704803467%
Epoch       13 Loss: 65.67037105560303%
Epoch       14 Loss: 64.68527913093567%
Epoch       15 Loss: 63.73901963233948%
Epoch       16 Loss: 62.8301203250885%
Epoch       17 Loss: 61.95717453956604%
Epoch       18 Loss: 61.118894815444946%
Epoch       19 Loss: 60.31391620635986%
Epoch       20 Loss: 59.54107046127319%
Epoch       21 Loss: 58.79910588264465%
Epoch       22 Loss: 58.08690786361694%
Epoch       23 Loss: 57.40333795547485%
Epoch       24 Loss: 56.74728751182556%
Epoch       25 Loss: 56.117719411849976%
Ep

Epoch      362 Loss: 0.3820533398538828%
Epoch      363 Loss: 0.3589754458516836%
Epoch      364 Loss: 0.3372172126546502%
Epoch      365 Loss: 0.3167143324390054%
Epoch      366 Loss: 0.29739802703261375%
Epoch      367 Loss: 0.279204617254436%
Epoch      368 Loss: 0.2620768966153264%
Epoch      369 Loss: 0.2459527924656868%
Epoch      370 Loss: 0.23078045342117548%
Epoch      371 Loss: 0.2165063749998808%
Epoch      372 Loss: 0.20308098755776882%
Epoch      373 Loss: 0.19045681692659855%
Epoch      374 Loss: 0.1785891712643206%
Epoch      375 Loss: 0.1674340688623488%
Epoch      376 Loss: 0.1569551764987409%
Epoch      377 Loss: 0.14710872201249003%
Epoch      378 Loss: 0.1378612476401031%
Epoch      379 Loss: 0.12917793355882168%
Epoch      380 Loss: 0.12102493783459067%
Epoch      381 Loss: 0.11337216710671782%
Epoch      382 Loss: 0.10619062231853604%
Epoch      383 Loss: 0.09945144411176443%
Epoch      384 Loss: 0.09313025511801243%
Epoch      385 Loss: 0.08719955803826451%
Epoch

Epoch      724 Loss: 3.552713678800501e-11%
Epoch      725 Loss: 3.552713678800501e-11%
Epoch      726 Loss: 3.552713678800501e-11%
Epoch      727 Loss: 3.552713678800501e-11%
Epoch      728 Loss: 3.552713678800501e-11%
Epoch      729 Loss: 3.552713678800501e-11%
Epoch      730 Loss: 3.552713678800501e-11%
Epoch      731 Loss: 3.552713678800501e-11%
Epoch      732 Loss: 3.206324095117452e-11%
Epoch      733 Loss: 3.552713678800501e-11%
Epoch      734 Loss: 2.8776980798284058e-11%
Epoch      735 Loss: 2.566835632933362e-11%
Epoch      736 Loss: 2.566835632933362e-11%
Epoch      737 Loss: 3.206324095117452e-11%
Epoch      738 Loss: 3.206324095117452e-11%
Epoch      739 Loss: 3.206324095117452e-11%
Epoch      740 Loss: 3.206324095117452e-11%
Epoch      741 Loss: 2.8776980798284058e-11%
Epoch      742 Loss: 2.8776980798284058e-11%
Epoch      743 Loss: 2.2737367544323206e-11%
Epoch      744 Loss: 2.566835632933362e-11%
Epoch      745 Loss: 2.566835632933362e-11%
Epoch      746 Loss: 1.99840

In [23]:
for input, target in zip(X, y):
    output = net(input)
    print("Input:[{},{}] Target:[{}] Predicted:[{}] Error:[{}]".format(
        int(input.cpu().data.numpy()[0][0]),
        int(input.cpu().data.numpy()[0][1]),
        int(target.cpu().data.numpy()[0]),
        round(float(output.cpu().data.numpy()[0]), 4),
        round(float(abs(target.cpu().data.numpy()[0] - output.cpu().data.numpy()[0])), 4)))

Input:[0,0] Target:[0] Predicted:[0.0] Error:[0.0]
Input:[0,1] Target:[1] Predicted:[1.0] Error:[0.0]
Input:[1,0] Target:[1] Predicted:[1.0] Error:[0.0]
Input:[1,1] Target:[0] Predicted:[0.0] Error:[0.0]


In [24]:
#from torchviz import make_dot, make_dot_from_trace
#make_dot(net(X[0]), params=dict(net.named_parameters()))